### ISSUE TITLE
Can pixi-particles be required after installing?

### ISSUE THREAD

**Issue by joseph-norman** [CloudKidStudio/PixiParticles#11]
I'm running into an issue where I'm attempting to load the `pixi-particles.js` file that is downloaded via Bower, like so:

In package.json (setting up alias for browser):
```
"browser": {
  "pixi-particles": "./lib/pixi-particles/dist/pixi-particles.js"
  ...
}
```

In source file:
```
var PP = require('pixi-particles');
```

I'm receiving an error saying it cannot find the module. Is this enabled when using PixiParticles?

Thanks

**Comment by andrewstart** [comment]
The Pixi Particles classes just live in a 'cloudkid' namespace - window.cloudkid.Emitter, etc.

**Comment by joseph-norman** [comment]
Cool - any plans to make it requireable?

**Comment by andrewstart** [comment]
We don't use browserify ourselves, so it would be something we'd have to look into adding in the future. If you could figure out what needs to be done and make a pull request, that would be awesome!

**Comment by joseph-norman** [comment]
I could take a look definitely as it would benefit me greatly.

**Comment by wajerrr** [comment]
Hi @joseph-norman I have been using PixiParticles for a while. it is great lib (without much of competition :-))
I was just wondering as you have closed  the issue. Does it mean is it fixed ? Can you use browsify with PixiParticles ?
