### ISSUE TITLE
setting frequency < 0 could crash page

### ISSUE THREAD

**Issue by lselden** [CloudKidStudio/PixiParticles#12]
If you set the spawn frequency to an invalid number ( < 0, and possibly a NaN ) then the update loop could end up crashing the page.  Perhaps there needs to be a sanity check (custom setter?) on frequency to enforce 0 if NaN or < 0?

**Comment by andrewstart** [comment]
The frequency actually needs to be > 0, because a value of 0 would still cause an infinite loop. That said, good catch, I've fixed this in release 1.5.1.
