### ISSUE TITLE
Starting Color and End Color not working

### ISSUE THREAD

**Issue by chelinho139** [CloudKidStudio/PixiParticles#19]
The starting color option and the end color option is not working.
I am using the white Pixel25px.png from the site.
How ever no matter that I set:
	"color": {
		"start": "1f62ff",
		"end": "3d6aff"
	},

It still shows only a horrible white pixel. Instead of a colored one.

Any help please?

**Comment by andrewstart** [comment]
Are you using a PIXI.ParticleContainer instead of a PIXI.Container? PIXI.ParticleContainer does not support tinting of its children, in the interest of speed, so colored particles require the use of PIXI.Container.

**Comment by chelinho139** [comment]
@andrewstart  thanks for answering. Yes, I was using ParticleContainer. And Yes it worked when switching to Container.
Could you please point that out in the documentation or the tutorial somewhere? it gave me a lot of trouble! and I searched everywhere before asking.
Thanks a lot ! cheers

**Comment by mirraj2** [comment]
@andrewstart I also just ran into this issue.  I think it is very intuitive to try using a particle container, so I think the docs should have a warning against using it.
