### ISSUE TITLE
Haxe Externs

### ISSUE THREAD

**Issue by Rollo-Liu** [CloudKidStudio/PixiParticles#21]
The email I send you months ago seems filtered... maybe. But I just noticed you can still receive messages here. So it's not actually an issue -- much more like a request.

Hi Andrew,

I've been working on a game by using Pixi.js and I like your Pixi Particles system. Thanks for the amazing library you guys made!

Our project is written in Haxe, so I made a Haxe externs for your library. I think @adireddy removed externs from his pixi-externs lib since Pixi.js v3 released. (don't know why but I can no longer find anything in his repo)

Therefore, if you don't mind would you please add my extern project page to your README.MD? It maybe easier for the others who needs this library in Haxe to find.

The project page:
http://github.com/Rollo-Liu/pixi-particles-haxe/

This is the lib page on Haxelib:
http://lib.haxe.org/p/pixi-particles/

If there is any problems please let me know.

Many thanks,

Chuan

**Comment by adireddy** [comment]
Hey @Rollo-Liu If you are interested in merging your externs in pixi-haxe I can add you as collaborator in that project. Better to keep everything in one place. You can add them to pixi/plugins section similar to pixi spine.

**Comment by Rollo-Liu** [comment]
Hi @adireddy ,

Sure, I'd like to. We have been using your pixi-extern quite a lot and I did a few merges too. Keep everything in one place is ideal. Especially my lib needs your lib as a dependency since it requires pixi API.

Once I'm in I'll create a pull request for the merge.

Cheers

**Comment by adireddy** [comment]
Can you click request access to pixi-haxe team from here https://github.com/orgs/pixijs/teams

**Comment by Rollo-Liu** [comment]
@adireddy It gives me an error: `You’re not a member of any teams in this organization.`

**Comment by adireddy** [comment]
ok added you now.. can you try creating a new branch for pixi-particles and add your classes.

**Comment by Rollo-Liu** [comment]
@adireddy  Will do. Thanks!
